version: 2
jobs:
 build:
   docker:  
     - image: circleci/ruby:2.4.1-jessie
   steps: 
     - checkout
 deploy: 
  docker: 
    - image: circleci/ruby:2.4.1-jessie
  steps:
    - checkout
    - run: 
        name: Deploy Master to Heroku 
        command: | 
            ls -l 
            #git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
            
