version: 2
jobs:
 build:
   docker:  
     - image: circleci/ruby:2.4.1-jessie
   steps: 
     - checkout
 deploy:
  machine:
   enabled: true
   working_directory: ~/reporting-api
   envrionment:
    HEROKU_APP: "testing-app-github-circleci"
  steps: 
    - checkout 
    - run: 
        name: Deploy master to Heroku 
        command: | 
          pwd
          ls -l 
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy: 
          requires:
            - build
